// The generated wire contract (Python `tui_gateway/contracts` is the single source of truth).
// Re-exported here because upstream's package.json does not list it in `exports`.
export type {
  AgentPluginRow,
  ApprovalChoice,
  ApprovalRequestParams,
  ApprovalResult,
  ClarifyQuestion,
  ClarifyRequestParams,
  ClarifyResult,
  CommandsCatalogParams,
  CommandsCatalogResult,
  ErrorPayload,
  GatewayReadyPayload,
  InflightTurn,
  MessageCompletePayload,
  NotificationShowPayload,
  OpenRequestEntry,
  PluginsManageParams,
  PluginsManageResult,
  PromptSubmitParams,
  PromptSubmitResult,
  RpcMethods,
  SecretRequestParams,
  SessionCreateParams,
  SessionCreateResult,
  SessionInterruptParams,
  SessionInterruptResult,
  SessionListParams,
  SessionListResult,
  SessionListRow,
  SessionLiveInfo,
  SessionResumeParams,
  SessionResumeResult,
  SessionTitlePayload,
  StatusUpdatePayload,
  StreamDeltaPayload,
  SubagentEventPayload,
  SubagentListResult,
  SudoRequestParams,
  ToolCompletePayload,
  ToolGeneratingPayload,
  ToolStartPayload,
  TranscriptMessage,
  TurnStatus,
  Usage,
  ValueResult
} from '../../../upstream/hermes-agent/apps/shared/src/gateway-contract.generated.ts'
